[package]
name = "floralis"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-runtime = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
log = "0.4"
chrono = { version = "0.4", features = ["clock"] }
ureq = { version = "2", features = ["json"] }
aes-gcm = "0.10"
sha2 = "0.10"
base64 = "0.22"
hostname = "0.4"
keyring = { version = "3", features = ["windows-native"] }
getrandom = "0.2"
image = "0.25"
urlencoding = "2"
winreg = "0.52"
winapi = { version = "0.3", features = ["tlhelp32", "processthreadsapi", "handleapi", "winnt", "winbase", "minwindef"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
